In [2]:
import numpy as np

size = 5
np_Array1 = np.full((size,size), 1)
np_Array2 = np.full((size,size), size)

output_array1 = np_Array1 + np_Array2
output_array2 = np.full((size,size), 0)

for i in range(size):
    for j in range(size):
        if i == j or (i+j) == (size-1):
            output_array2[i][j] = output_array1[i][j] ** 2
        else:
            output_array2[i][j] = output_array1[i][j]

print("\n[ 출력결과1 ]")
print(output_array1)

print("\n[ 출력결과2 ]")
print(output_array2)



[ 출력결과1 ]
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]

[ 출력결과2 ]
[[36  6  6  6 36]
 [ 6 36  6 36  6]
 [ 6  6 36  6  6]
 [ 6 36  6 36  6]
 [36  6  6  6 36]]


In [ ]:

[ 출력결과1 ]
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]

[ 출력결과2 ]
[[36  6  6  6 36]
 [ 6 36  6 36  6]
 [ 6  6 36  6  6]
 [ 6 36  6 36  6]
 [36  6  6  6 36]]
